FROM node:12

WORKDIR /usr/src/app

COPY . .


RUN sed -i 's/stretch/buster/' /etc/apt/sources.list && apt update && apt install -y zip
RUN echo 'deb http://security.debian.org/ stretch/updates main contrib non-free' > /etc/apt/sources.list
RUN echo 'deb http://security.debian.org/debian-security stable-security/updates main' > /etc/apt/sources.list
RUN npm install && npm run build

RUN zip -r dist.zip dist

