FROM node:12
ENV NODE_OPTIONS="--max-old-space-size=16384"

WORKDIR /usr/src/app

COPY . .


RUN sed -i '/stretch-updates/d' /etc/apt/sources.list && \
    sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list && \
    sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list && \
    echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until && \
    apt update && \
    apt install -y zip libjpeg-turbo-progs nasm
RUN apt update && apt install -y zip

RUN npm install && npm run build

RUN zip -r dist.zip dist

