// tslint:disable-next-line: all
const env = process.env;
const HTTPS_HOST = env.HTTPS_HOST || 'https://aastrika-sb.idc.tarento.com'
export const CONSTANTS = {
  AES_ENCRYPTION_METHOD: env.AES_ENCRYPTION_METHOD || 'abc',
  AES_ENCRYPTION_SECRET: env.AES_ENCRYPTION_SECRET || 'abc',
  AES_SECRET_IV: env.AES_SECRET_IV || 'abc',
  AES_SECRET_KEY: env.AES_SECRET_KEY || 'abc',
  APP_SSO_KEYCLOAK_SECRET: env.APP_SSO_KEYCLOAK_SECRET,
  APP_VERSION_PATH: env.APP_VERSION_PATH || 'abc',

  BNRC_MSG91_TEMPLATE_ID: env.BNRC_MSG91_TEMPLATE_ID || '',
  BNRC_USER_DEFAULT_PASSWORD: env.BNRC_USER_DEFAULT_PASSWORD || '',
  BULK_USER: env.BULK_USER || 'Sunbird@123',

  IS_CASSANDRA_AUTH_ENABLED: Boolean(env.CASSANDRA_AUTH_ENABLED),
  CASSANDRA_IP: env.CASSANDRA_IP || '',
  CASSANDRA_PASSWORD: env.CASSANDRA_PASSWORD || '',
  CASSANDRA_USERNAME: env.CASSANDRA_USERNAME || '',
  CDN_DOMAIN: env.CDN_DOMAIN,
  CERTIFICATE_DOWNLOAD_KEY: env.CERTIFICATE_DOWNLOAD_KEY,
  COHORTS_API_BASE: env.COHORTS_API_BASE || env.SB_EXT_API_BASE_2,
  COMPETENCY_API_BASE: env.COMPETENCY_API_BASE || 'http://compentency-tool-service:8080',
  COMPETENCY_ROLES_MAPPING_PATH: env.COMPETENCY_ROLES_MAPPING_PATH || '',
  COMPETENCY_ROLES_DATA_PATH: env.COMPETENCY_ROLES_WISE_DATA_PATH || '',
  CONTENT_API_BASE: env.CONTENT_API_BASE || 'http://localhost:5903',
  CONTENT_SERVICE_API_BASE: env.CONTENT_SERVICE_API_BASE || 'http://content-service:9000',
  CONTENT_VALIDATION_API_BASE: env.CONTENT_VALIDATION_API_BASE || 'http://localhost:6590',
  CONTINUE_LEARNING_API_BASE:
    env.CONTINUE_LEARNING_API_BASE || env.SB_EXT_API_BASE_2,

  DATA_LAKE_POSTGRES_DATABASE: env.DATA_LAKE_POSTGRES_DATABASE,
  DATA_LAKE_POSTGRES_HOST: env.DATA_LAKE_POSTGRES_HOST,
  DATA_LAKE_POSTGRES_PASSWORD: env.DATA_LAKE_POSTGRES_PASSWORD,
  DATA_LAKE_POSTGRES_PORT: env.DATA_LAKE_POSTGRES_PORT,
  DATA_LAKE_POSTGRES_USER: env.DATA_LAKE_POSTGRES_USER,
  DECRYPTION_API_BASE: env.DECRYPTION_API_BASE || 'http://decryption-service:8084',
  DEFAULT_ORG: env.DEFAULT_ORG || 'dopt',
  DEFAULT_ROOT_ORG: env.DEFAULT_ROOT_ORG || 'igot',
  DHURVA_BHASHINI_API_BASE: env.DHURVA_BHASHINI_API_BASE || 'https://dhruva-api.bhashini.gov.in',
  DISCUSSION_CATEGORY_LIST: env.DISCUSSION_CATEGORY_LIST || 'cid[]=5&cid[]=6&cid[]=8&cid[]=9&cid[]=10&cid[]=11&cid[]=12&cid[]=13',
  DISCUSSION_HUB_API_BASE: env.DISCUSSION_HUB_API_BASE || 'http://localhost:4567',
  DISCUSSION_HUB_DEFAULT_PASSWORD: env.DISCUSSION_HUB_DEFAULT_PASSWORD || 'nodebbUser123$',
  DISCUSSION_HUB_MIDDLEWARE: env.DISCUSSION_HUB_MIDDLEWARE || 'http://localhost:3002',
  DISCUSSION_HUB_WRITE_API_KEY: env.DISCUSSION_HUB_WRITE_API_KEY || '5aaf0ac3-c7ad-4e06-bc1b-5311d462cef3',
  DISCUSSION_HUB_WRITE_API_UID: env.DISCUSSION_HUB_WRITE_API_UID || 1,

  EKSHAMATA_SECURITY_KEY_MASTER: env.EKSHAMATA_SECURITY_KEY_MASTER || '',
  ENTITY_API_BASE: env.ENTITY_API_BASE || 'http://10.1.2.120:8083',
  ES_IP: env.ES_IP || '10.1.1.131:9200',

  FEEDBACK_API_BASE: env.FEEDBACK_API_BASE || env.SB_EXT_API_BASE_2,
  FORM_API_BASE: env.FORM_API_BASE || 'http://localhost:3004',
  FRAC_API_BASE: env.FRAC_API_BASE || 'https://igot-frac-dev.tarento.com',
  FIREBASE_PROJECT_ID: env.FIREBASE_PROJECT_ID || '',
  FIREBASE_PRIVATE_KEY: env.FIREBASE_PRIVATE_KEY ? env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n') : '',
  FIREBASE_CLIENT_EMAIL: env.FIREBASE_CLIENT_EMAIL || '',

  GOALS_API_BASE: env.GOALS_API_BASE || env.SB_EXT_API_BASE_2,

  HTTPS_HOST,

  IAP_CLIENT_SECRET: env.IAP_CLIENT_SECRET,
  IAP_CODE_API_BASE: env.IAP_CODE_API_BASE || '',
  ILP_FP_PROXY: env.ILP_FP_PROXY || 'http://localhost:port',
  INTEREST_API_BASE: env.INTEREST_API_BASE || env.SB_EXT_API_BASE_2,

  JUGALBANDI_API_BASE: env.JUGALBANDI_API_BASE || 'http://localhost:8086',

  KC_NEW_USER_DEFAULT_PWD: env.KC_NEW_USER_DEFAULT_PWD || 'User@123',
  KEYCLOAK_ADMIN_PASSWORD: env.KEYCLOAK_ADMIN_PASSWORD || '',
  KEYCLOAK_ADMIN_USERNAME: env.KEYCLOAK_ADMIN_USERNAME || '',
  KEYCLOAK_CLIENT_SECRET_MATERNITY_FOUNDATION: env.KEYCLOAK_CLIENT_SECRET_MATERNITY_FOUNDATION,
  KEYCLOAK_CLIENT_SECRET_MNC: env.KEYCLOAK_CLIENT_SECRET_MNC || '',
  KEYCLOAK_CLIENT_SECRET_SASHAKT: env.KEYCLOAK_CLIENT_SECRET_SASHAKT,
  KEYCLOAK_CLIENT_SECRET_TNAI: env.KEYCLOAK_CLIENT_SECRET_TNAI || '',
  KEYCLOAK_CLIENT_SECRET_TNNMC: env.KEYCLOAK_CLIENT_SECRET_TNNMC || '',
  KEYCLOAK_REALM: env.KEYCLOAK_REALM || 'sunbird',
  KEYCLOAK_REDIRECT_URL: env.KEYCLOAK_REDIRECT_URL || 'https://requestbin.io/',
  KEYCLOAK_SESSION_TTL: 30 * 24 * 60 * 60 * 1000,
  KHUB_SEARCH_BASE: env.KHUB_SEARCH_BASE || 'http://localhost:3014',
  KNOWLEDGE_MW_API_BASE: env.KNOWLEDGE_MW_API_BASE || 'http://knowledge-mw-service:5000',
  KONG_API_BASE: env.KONG_API_BASE || 'https://sphere.aastrika.org/api',

  // LA_HOST_PROXY env assigned
  APP_ANALYTICS: env.LA_HOST_PROXY || 'http://localhost:portNUmber',
  LEARNING_HISTORY_API_BASE:
    env.LEARNING_HISTORY_API_BASE || env.SB_SEXT_API_BASE_3,
  LEARNING_HUB_API_BASE: env.LEARNING_HUB_API_BASE || env.SB_EXT_API_BASE_2,
  LIKE_API_BASE: env.LIKE_API_BASE || env.SB_EXT_API_BASE_2,

  MATERNITY_FOUNDATION_ACCESS_KEY: env.MATERNITY_FOUNDATION_ACCESS_KEY,
  MATERNITY_FOUNDATION_USER_DETAILS_URL: env.MATERNITY_FOUNDATION_USER_DETAILS_URL,
  MEITY_AUTH_ULCACONTRIB: env.MEITY_AUTH_ULCACONTRIB || 'https://meity-auth.ulcacontrib.org',
  MNC_JWT_SECRET: env.MNC_JWT_SECRET || '',
  MSG_91_AUTH_KEY_SSO: env.MSG_91_AUTH_KEY_SSO || '',
  MSG_91_TEMPLATE_ID_SEND_OTP_SSO: env.MSG_91_TEMPLATE_ID_SEND_OTP_SSO || '',
  MULTI_TENANT_KEYCLOAK: env.MULTI_TENANT_KEYCLOAK || 'igot,https://igot-dev.in/auth,sunbird',

  NETWORK_HUB_SERVICE_BACKEND: env.NETWORK_HUB_SERVICE_BACKEND || 'http://localhost:3013',
  NODE_API_BASE: env.NODE_API_BASE || 'http://localhost:5001',
  NODE_API_BASE_3: env.NODE_API_BASE_3 || 'http://localhost:3015',
  IS_DEVELOPMENT: env.NODE_ENV === 'development',
  NOTIFICATIONS_API_BASE: env.NOTIFICATIONS_API_BASE || 'http://localhost:5805',

  OTP_EXTRACTION_KEY: env.OTP_EXTRACTION_KEY || '',

  PIPE_LINE_ID: env.PIPE_LINE_ID || '64392f96daac500b55c543cd',
  PIPE_LINE_USER_ID: env.PIPE_LINE_USER_ID || '8dc9f708bd144d78b2e423f7be1bcd8a',
  PLAYLIST_API_BASE: env.PLAYLIST_API_BASE || env.SBEXT_API_BASE,
  POSTGRES_DATABASE: env.POSTGRES_DATABASE,
  POSTGRES_HOST: env.POSTGRES_HOST,
  POSTGRES_PASSWORD: env.POSTGRES_PASSWORD,
  POSTGRES_PORT: env.POSTGRES_PORT,
  POSTGRES_USER: env.POSTGRES_USER,
  PREFERENCE_API_BASE: env.PREFERENCE_API_BASE || env.SB_EXT_API_BASE_4,
  PROFANITY_SERVICE_API_BASE: env.PROFANITY_SERVICE_API_BASE || 'http://localhost:4001',
  PROGRESS_API_BASE: env.PROGRESS_API_BASE || env.SB_EXT_API_BASE_2,

  RATING_API_BASE: env.RATING_API_BASE || env.SB_EXT_API_BASE_2 || 'http://localhost:7001',
  RC_MAPPER_HOST: env.RC_MAPPER_HOST,
  RC_S3_ACCESS_KEY_ID: env.RC_S3_ACCESS_KEY_ID,
  RC_S3_BUCKET_NAME: env.RC_S3_BUCKET_NAME,
  RC_S3_SECRET_ACCESS_KEY: env.RC_S3_SECRET_ACCESS_KEY,
  RECOMMENDATION_API_BASE_V2: env.RECOMMENDATION_API_BASE_V2 || 'http://localhost:8086',
  ROLES_API_BASE: env.ROLES_API_BASE || env.SB_EXT_API_BASE_2,

  S3_BUCKET_URL: env.S3_BUCKET_URL || 'https://sunbirdcontent.s3-ap-south-1.amazonaws.com/',
  S3_DOMAIN: env.S3_DOMAIN,
  SASHAKT_USER_DETAILS_URL: env.SASHAKT_USER_DETAILS_URL,
  SB_API_KEY: env.SB_API_KEY || '',
  SB_EXT_API_BASE_2: env.SBEXT_API_BASE_2 || 'http://localhost:7001',
  SB_EXT_API_BASE: env.SBEXT_API_BASE || 'http://localhost:5902',
  SB_EXT_API_BASE_3: env.SBEXT_API_BASE_3 || env.SBEXT_API_BASE_2 || 'http://localhost:7002',
  SB_EXT_API_BASE_4: env.SBEXT_API_BASE_4 || env.SBEXT_API_BASE_2 || env.SB_EXT_BASE_4 || 'http://localhost:7002',
  SCORING_SERVICE_API_BASE: env.SCORING_SERVICE_API_BASE || 'http://localhost:7014',
  SELF_SERVICE_PORTAL_API_BASE: env.SELF_SERVICE_PORTAL_API_BASE || '',
  STATIC_ILP_PROXY: env.STATIC_ILP_PROXY || 'http://localhost:3005',
  SUBMISSION_API_BASE: env.SUBMISSION_API_BASE || env.SB_EXT_API_BASE_2,
  AUTHORING_BACKEND: env.SUNBIRD_BACKEND || 'http://localhost:3011',
  SUNBIRD_PROXY_URL: env.SUNBIRD_PROXY_URL || 'https://igot-sunbird.idc.tarento.com/apis/proxies/v8/action',
  SUNBIRD_PROXY_API_BASE: env.SUNBIRD_PROXY_API_BASE || 'https://igot-dev.in/api',

  TELEMETRY_API_BASE: env.TELEMETRY_API_BASE || 'http://localhost:8090',
  TELEMETRY_SB_BASE: env.TELEMETRY_SB_BASE || 'http://localhost:9090',
  TIMEOUT: env.TIMEOUT || 10000,
  TIMESPENT_API_BASE: env.TIMESPENT_API_BASE || env.SB_EXT_API_BASE_2,
  TNAI_ACCESS_KEY: env.TNAI_ACCESS_KEY || '',
  TNAI_USER_DETAILS_URL: env.TNAI_USER_DETAILS_URL || '',
  TNC_API_BASE: env.TNC_API_BASE || env.SB_EXT_API_BASE_4,
  TNNMC_API_KEY: env.TNNMC_API_KEY || '',
  TNNMC_API_SECRET: env.TNNMC_API_SECRET || '',
  TNNMC_USER_DETAILS_URL: env.TNNMC_USER_DETAILS_URL || '',

  ULC_API_KEY: env.ULC_API_KEY || '32b08e5927-ed2c-4125-beac-862a01fee6f2',
  USER_DEACTIVATION_KEY: env.USER_DEACTIVATION_KEY || '',
  USER_DETAILS_API_BASE: env.USER_DETAILS_API_BASE || env.SB_EXT_API_BASE_2,
  USER_PROFILE_API_BASE: env.USER_PROFILE_API_BASE || 'http://localhost:3004',
  USER_REPORTING_SERVICE: env.USER_REPORTING_SERVICE,

  VIEWER_PLUGIN_RDBMS_API_BASE: process.env.VIEWER_PLUGIN_RDBMS_API_BASE || 'http://localhost:5801',
  VM_LEARNING_SERVICE_URL: env.VM_LEARNING_SERVICE_URL,

  WEB_HOST_PROXY: env.WEB_HOST_PROXY || 'http://localhost:3007',
  WORKFLOW_HANDLER_SERVICE_API_BASE: env.WORKFLOW_HANDLER_SERVICE_API_BASE || 'http://localhost:5099',

  KEYCLOAK_CLIENT_SECRET: env.client_secret,
  X_Channel_Id: env.X_CHANNEL_ID || '',

  // label constants
  NOTIFY_SEND_FOR_REVIEW_BODY:
    'You have received request to review the content #contentLink',
  NOTIFY_REVIEW_FAILED:
    'The content #contentLink which sent for review requires few more changes. Please contact the reviewers.',
  NOTIFY_REVIEW_COMPLETED_BODY:
    'The content #contentLink is successfully reviewed and sent to publishers to publish the Content.',
  NOTIFY_SEND_FOR_PUBLISH_BODY:
    'You have received request to publish the content #contentLink',
  NOTIFY_PUBLIST_FAILED:
    'The content #contentLink which sent for publish requires few more changes. Please contact the publishers.',
  NOTIFY_PUBLISH_COMPLETED_BODY:
    'The content #contentLink is successfully published.' +
    ' The content will be available for the users in few hours.',
  NOTIFY_EMAIL_TEMPLATE_ID: 'emailtemplate',

  KB_TIMEOUT: env.KB_TIMEOUT || 60000,
  ANALYTICS_TIMEOUT: env.ANALYTICS_TIMEOUT || 10000,
  CLUSTER_THREAD: env.CLUSTER_THREAD || 1,
  CORS_ENVIRONMENT: env.CORS_ENVIRONMENT || 'prod',
  PORTAL_API_WHITELIST_CHECK: env.PORTAL_API_WHITELIST_CHECK || 'false',
  PORTAL_PORT: parseInt(env.PORTAL_PORT + '', 10) || 3003,
  CASSANDRA_REPLICATION_FORM: env.CASSANDRA_REPLICATION_FORM || 3,
  PORTAL_CASSANDRA_CONSISTENCY_LEVEL: env.PORTAL_CASSANDRA_CONSISTENCY_LEVEL || 'one',

  // TODO: need to verify
  ACCESS_CONTROL_API_BASE: env.ACCESS_CONTROL_API_BASE || env.SBEXT_API_BASE,
ATTENDANCE_API_BASE: env.ATTENDANCE_API_BASE || env.SB_EXT_API_BASE_2,
COUNTER: 'http://localhost:5903',
// not in the md file list
CONTENT_META_FETCH_API_BASE: env.CONTENT_META_FETCH_API_BASE || 'http://localhost:5906',

ES_BASE: env.ES_BASE || 'http://localhost:9200',
ES_PASSWORD: env.ES_PASSWORD || 'iGOT@123+',
ES_USERNAME: env.ES_USERNAME || 'elastic',

GOOGLE_CLIENT_ID: env.google_client_id || '',
//  not in the md file list
GAMIFICATION_API_BASE: env.GAMIFICATION_API_BASE || 'http://localhost:port-number',

IAP_BACKEND_AUTH: env.IAP_BACKEND_AUTH || '',

LEARNER_SERVICE_API_BASE: env.LEARNER_SERVICE_API_BASE || 'http://learner-service:9000',

MSG91BASE: env.MSG91BASE || 'http://localhost:3300',
MSG91KEY: env.MSG91KEY || 'http://localhost:3301',
MSG91TEMPLATEID: env.MSG91TEMPLATEID || 'http://localhost:3302',

NOTIFICATION_ENGINE_API_BASE: env.NOTIFICATION_ENGINE_API_BASE || 'http://localhost:3013',
NOTIFICATION_SERVIC_API_BASE: env.NOTIFICATION_SERVIC_API_BASE || 'http://notification-service:9000',

PLAYLISTV1_API_BASE: env.PLAYLISTV1_API_BASE || env.SBEXT_API_BASE_2,
POST_ASSESSMENT_BASE: env.POST_ASSESSMENT_BASE || 'http://localhost.com',
POST_ASSESSMENT_CLIENT_ID: env.POST_ASSESSMENT_CLIENT_ID || '',
POST_ASSESSMENT_CLIENT_SECRET: env.POST_ASSESSMENT_CLIENT_SECRET || '',

  RECOMMENDATION_API_BASE: env.RECOMMENDATION_API_BASE || env.SBEXT_API_BASE,
  REGISTRY_API_BASE: env.REGISTRY_API_BASE,
  RESET_PASSWORD: '',
  SCORM_PLAYER_BASE: env.SCORM_PLAYER_BASE || 'http://localhost:port',
  SEARCH_API_BASE: env.SEARCH_API_BASE || env.SBEXT_API_BASE,
  SOCIAL_TIMEOUT: env.SOCIAL_TIMEOUT || 10000,
USER_ANALYTICS: `${HTTPS_HOST}/LA1`,

USER_BULK_UPLOAD_DIR: env.USER_BULK_UPLOAD_DIR,
USER_CREATE_API_BASE: env.USER_CREATE_API_BASE,
  USER_CREATE_PASSWORD: env.USER_CREATE_PASSWORD || 'C9Mg4@0q!J',
  USER_CREATE_USERNAME: env.USER_CREATE_USERNAME || 'ui-client',
  USE_SERVING_HOST_COUNTER: env.USE_SERVING_HOST_COUNTER,

}

export const RESTRICTED_PYTHON_STMT: string[] = process.env
  .RESTRICTED_CHARACTERS
  ? process.env.RESTRICTED_CHARACTERS.split('###')
  : []
