name: Unit Test Runner
on:
  pull_request:
    branches:
      - development
      - cbrelease-4.0.1
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    environment : sonarcloud
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test
      - name: Coverage
        run: npm run test-with-coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version:
  #         - 14.x
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: npm
  #     - run: npm install
  #     - run: npm run test-with-coverage
